### ISSUE TITLE
[1MD] 메인페이지 리팩토링

### ISSUE THREAD

**Issue by inthewalter** [connect-foundation/2019-12#161]
### Page

MainPage

### Todo

- [x] 헤더 반응형 대응
- [x] 카드 컴포넌트 수정
- [x] rootMargin 수정해서 인피니티 스크롤 조금 더 매끄럽게 수정
- [x] 딜레이 함수 유틸화
- [x] 커스텀 훅 수정

**Comment by inthewalter** [comment]
#174  completed
